language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: jB57Bn19EIu4dbfVYR2d75mDmi8iaxsXYObJBttZK+4OZ5uvkmAHNGaCrg9os7GjOXxAhcqqFHI3GQQPMAyXFXCQ2l/ggs62VRk3l5h2JXXQDzOX+uej3tZUJ6gdZJB9C+fq33XPK1OtBwgCPgqQKpJ1CgxtmLnngcz60XLUzfEHPOkMRL3jX/A7dTrcu5a4i8TE0E0TTiv/S38NYAOiSaWqZiUDF1qoGLYYlwiu5vD6vLcuxhZepe+xxWQlVEZBXO+g9BD5XLRwWl32X1N2szF9Tpkuev8WlmJUsZRkrBAQNyOPHQnNM9cJ3DfH1fw+A+lxXJlh3SuTQ6joZiEj9/CFXL8VbNPl6yC9e2gw4tvESlRxF4Lw0cdOeGBrWTDvrrecaJdMjg2eQIqNyXp6PNcvCdLtapYNWZ7WGNjX3MN5Rhvg0RguyLG22z2UuA1lE5hUohVb5zig+E0GL3XpDlybAZac1xT/qi+FtZ0nL3qpYif7Z08OEoHX7/gqUQv7hnsu7klynUUbS3gOM+K86aCfFp9XkTsmTH7UidlfSkE6hu5FqkPLAJ1H8wCOXYSCCNezvb1tedJ8kDGR7QpAIAj7Z56VNx5S7Fcb09LgvPOUnkZ4KrmYRHyxo58hRDjKZ/NK17s7bmPZd3GJGaJIuaWkPR/VqG3dL6WJP/24nUA=
