language: csharp
mono:
- latest
install:
- nuget restore
script:
- xbuild /p:Configuration=CI Com.Latipium.Template.sln
env:
  secure: M0/qRovv8SdTNpKZVYx1CF7vHIqhcc2v9mJM49nF2P2DDNPI4rJM1xSV1I50X9gFtBUlpasdJAxIZ9YRwo3Hj0nEdeNvStT3B1nZkA28Q5Bsots1ZQnZFULMAUDfO9yW7/QgD1N87lK6wvp0J9SoflCaAzSFMN+OiyCb3l9HzRjpRHLpO/RMJvKg6SQHrQtDErfL5U1touOagKSXWmo+wrMQ10w5pJ2rRJkD1tApTErfi04+oadmbxCVpJt/s952LIuvAmH9tiH+2nV/M4JaiWEB3AkowmHkMhilGfmq02pf1U91roVGQ+PDUTD2vv1KDlznTWNJsj6O5BfgJhjORYIe12cDweFPMglHRBxO5Jdmj1Y2JB50CTnQVjLcVTBFjVb0ERburIescWPhqlNGd3lxM6L8nnEcf+C5s5xRTLU3RejPkPz08K55jur06CZT7XOtzSkn4G0ZqW6Lqm1B0objqTGfdoEUe84I+npbtcq8gh/fQZRxtQjO/iPvZ/YzyHVl/mO3j818Dc0ptP3VckPyF4T7vX/iFhHZtlLDuq3HfyCg+DF3tyI8vEjFWNBR0UMqXWN0zloCco+jmpvhfytAaDiQHAu5a0G/8lBW4DbXMFBGk35Yeg9Us5RUUWcl42u7j7ZedS3/g6OroXOEHzAofEx9MAqrv07ibO0hU4c=
