//
// FileVersioner.cs
//
// Author:
//       Zach Deibert <zachdeibert@gmail.com>
//
// Copyright (c) 2016 Zach Deibert
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
using System;
using System.IO;
using System.Text.RegularExpressions;

namespace Com.Latipium.DevTools.Versioning {
    /// <summary>
    /// Versions a C# AssemblyVersion.cs file.
    /// </summary>
    public class FileVersioner {
        /// <summary>
        /// The filename.
        /// </summary>
        public readonly string Filename;
        /// <summary>
        /// The version.
        /// </summary>
        public readonly Version Version;

        /// <summary>
        /// Gets a value indicating whether this file exists.
        /// </summary>
        /// <value><c>true</c> if it exists; otherwise, <c>false</c>.</value>
        public bool Exists {
            get {
                return File.Exists(Filename);
            }
        }

        /// <summary>
        /// Replaces all version tags in the file.
        /// </summary>
        public void ReplaceAll() {
            string contents;
            using (TextReader reader = new StreamReader(Filename)) {
                contents = reader.ReadToEnd();
            }
            contents = Regex.Replace(contents, "([^A-Za-z0-9])AssemblyVersion([ \t]*)\\(([ \t]*)\"[^\"]*\"([ \t]*)\\)", string.Format("$1AssemblyVersion$2($3\"{0}\"$4)", Version));
            using (TextWriter writer = new StreamWriter(Filename)) {
                writer.Write(contents);
            }
        }

        /// <summary>
        /// Creates the file.
        /// </summary>
        public void Create() {
            using (TextWriter writer = new StreamWriter(Filename)) {
                writer.WriteLine("// This file was auto-generated by the Latipium Development Tools");
                writer.WriteLine("// Make sure this is in your .gitignore file!");
                writer.WriteLine("using System.Reflection;");
                writer.WriteLine();
                writer.WriteLine("[assembly: AssemblyVersion(\"{0}\")]", Version);
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Com.Latipium.DevTools.Versioning.FileVersioner"/> class.
        /// </summary>
        /// <param name="filename">The filename.</param>
        /// <param name="version">The version.</param>
        public FileVersioner(string filename, Version version) {
            Filename = filename;
            Version = version;
        }
    }
}

